---
openapi: 3.0.0
info:
  description: |
    This is a sample server STATAPI server.
  version: v1
  title: STATAPI-Public
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    # email: apiteam@swagger.io
    url: http://statapi-test.azurewebsites.net/
  x-logo:
    # url: 'http://127.0.0.1:5501/logo.png'
    url: 'https://github.com/ArulEST/STATAPI_Public/blob/main/logo.png'
    altText: STAT logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

# host: 
#   http://statapi-test.azurewebsites.net/
# schemes:
#  - http

tags:
  - name: Orders
    description: |
      The Orders module is designed to streamline the management of orders within the application. It provides a comprehensive set of endpoints and functionalities that allow users to create, retrieve, update, and delete orders. This module serves as the backbone for order processing, ensuring a seamless and efficient experience for the customers and administrators. 
      
      
      Key features of the Orders module include: 


        •	**Order Creation:** Users can submit new orders through dedicated endpoints, specifying essential details such as collection and delivery location, quantities and price and tracking information. 
      
      
        •	**Order Retrieval:** Retrieve detailed information about existing orders, including order tracking number, status, collection and delivery location, and customer details. 
      
      
        •	**Order Modification:** Update order information, such as quantities, signature flag through secure and straightforward endpoints. 
      
      
        •	**Order Deletion:** When necessary, users can cancel orders, and the module handles the necessary updates and notifications. 
      
      
        •	**Order Status Tracking:** Easily monitor the status of orders, from creation to shipment and delivery, enabling real-time order tracking for customers and staff. 
  - name: CreateOrderInDto_model
    x-displayName: The Create Order Request Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/CreateOrderInDto" />    
  # - name: Collectionlocation_model
  #   x-displayName: The Collection location Model
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/Collectionlocation" />
  # - name: Deliverylocation_model
  #   x-displayName: The Delivery location Model
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/Deliverylocation" />
  # - name: OnTimePriceModifier_model
  #   x-displayName: The OnTime PriceModifier Model
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/OnTimePriceModifier" />

  - name: CreateOrderOutDto_model
    x-displayName: The Create Order Response Model
    description: |
      <SchemaDefinition schemaRef="#/components/schemas/CreateOrderOutDto" />    
  # - name: OrderStatusDto_model
  #   x-displayName: The OrderStatusDto Model
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/OrderStatusDto" />
  # - name: CollectionArrivalWindow_model
  #   x-displayName: The CollectionArrivalWindow Model
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/CollectionArrivalWindow" />
  # - name: DeliveryArrivalWindow_model
  #   x-displayName: The OnTime DeliveryArrivalWindow Model
  #   description: |
  #     <SchemaDefinition schemaRef="#/components/schemas/DeliveryArrivalWindow" />    


x-tagGroups:
  - name: General
    tags:
      - Orders
  - name: Models
    tags:
      - CreateOrderInDto_model  
      # - Collectionlocation_model   
      # - Deliverylocation_model   
      # - OnTimePriceModifier_model  
     
      - CreateOrderOutDto_model
      # - OrderStatusDto_model   
      # - CollectionArrivalWindow_model   
      # - DeliveryArrivalWindow_model 
     
paths:
  /api/orders:
    post:
      tags:
      - Orders
      summary: Create order.
      operationId: Orders_CreateOrder
      description: This API endpoint facilitates the creation of a customer's order by capturing essential information such as quantities, prices, and location details. 
      parameters:
        - in: body
          name: orderDto
          # description: Fill the CreateOrderInDto object (JSON format).
          required: true
          schema:
            $ref: '#/components/schemas/CreateOrderInDto'
      responses:
        "200":
          description: OK successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateOrderOutDto'
        "400":
          description: BadRequest
      requestBody:
        name: customerDto
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderInDto'
        description: Order request body schema description.
        required: true 
 
components:
  schemas:
    Collectionlocation:
      type: object
      required:
        - AddressLine1
        - AddressLine2
        - City
        - CompanyName
        - ContactName
        - Country
        - Email
        - Phone
        - PostalCode
        - State
      properties:
        Zone:
          type: string
          description: The name of the collection zone
          minLength: 0
          maxLength: 50
        ID:
          type: string
          description: Unique id generated by the STAT system. This is used as identifier
          minLength: 0
          maxLength: 50
        ContactName:
          type: string
          description: Name of the contact person of collection location 
          minLength: 0
          maxLength: 50
        CompanyName:
          type: string
          description: Name of the company of the collection location 
          minLength: 0
          maxLength: 50
        AddressLine1:
          type: string
          description: Line 1 of the collection location 
          minLength: 0
          maxLength: 50
        AddressLine2:
          type: string
          description: Line 2 of the collection location 
          minLength: 0
          maxLength: 50
        City:
          type: string
          description: City of the collection location 
          minLength: 0
          maxLength: 50
        State:
          type: string
          description: State of the collection location  
          minLength: 0
          maxLength: 50
        PostalCode:
          type: string
          description: Postal code of the collection location 
          minLength: 0
          maxLength: 50
        Country:
          type: string
          description: Country of the delivery location 
          minLength: 0
          maxLength: 50
        Comments:
          type: string
          description: Free text field to input the additional information 
          minLength: 0
          maxLength: 512
        Email:
          type: string
          description: Email address of the contact person
          minLength: 0
          maxLength: 512
        Phone:
          type: string
          description: Phone number of the contact person in collection 
          minLength: 
          maxLength: 50
        Category:
          type: string
          description: Category
          minLength: 0
          maxLength: 256
        LatitudeLongitude:
          type: string
          description: Lat & Long coordinates to collect the package and collection the package 
          minLength: 0
          maxLength: 100
      example:
        Zone: ""
        ID: ""
        ContactName: "Johnsons-6"
        CompanyName: "Johnsons-6"
        AddressLine1: "2334 Cedar Crest Blvd"
        AddressLine2: ""
        City: "Dallas"
        State: "TX"
        PostalCode: "75203"
        Country: "United States"
        Comments: null
        Email: "pharma@yopmail.com"
        Phone: "3333344445"
        Category: null
        LatitudeLongitude: null
      xml:
        name: Collectionlocation
    Deliverylocation:
      type: object
      required:
        - AddressLine1
        - AddressLine2
        - City
        - CompanyName
        - ContactName
        - Country
        - Email
        - Phone
        - PostalCode
        - State
      properties:
        Zone:
          type: string
          description: The name of the delivery zone
          minLength: 0
          maxLength: 50
        ID:
          type: string
          description: Unique id generated by the STAT system. This is used as identifier
          minLength: 0
          maxLength: 50
        ContactName:
          type: string
          description: Name of the contact person of delivery location 
          minLength: 0
          maxLength: 50
        CompanyName:
          type: string
          description: Name of the company of the delivery location 
          minLength: 0
          maxLength: 50
        AddressLine1:
          type: string
          description: Line 1 of the delivery location 
          minLength: 0
          maxLength: 50
        AddressLine2:
          type: string
          description: Line 2 of the delivery location 
          minLength: 0
          maxLength: 50
        City:
          type: string
          description: City of the delivery location 
          minLength: 0
          maxLength: 50
        State:
          type: string
          description: State of the delivery location  
          minLength: 0
          maxLength: 50
        PostalCode:
          type: string
          description: Postal code of the delivery location 
          minLength: 0
          maxLength: 50
        Country:
          type: string
          description: Country of the delivery location 
          minLength: 0
          maxLength: 50
        Comments:
          type: string
          description: Free text field to input the additional information 
          minLength: 0
          maxLength: 512
        Email:
          type: string
          description: Email address of the contact person
          minLength: 0
          maxLength: 512
        Phone:
          type: string
          description: Phone number of the contact person in delivery 
          minLength: 0
          maxLength: 50
        Category:
          type: string
          description: Category
          minLength: 0
          maxLength: 256
        LatitudeLongitude:
          type: string
          description: Lat & Long coordinates to collect the package and deliver the package 
          minLength: 0
          maxLength: 100
      example:
        Zone: ""
        ID: ""
        ContactName: "Tom Holland-525"
        CompanyName: "Medicare-525"
        AddressLine1: "9050 Markville Dr"
        AddressLine2: ""
        City: "Dallas"
        State: "TX"
        PostalCode: "75243"
        Country: "United States"
        Comments: null
        Email: "uzumaki@yopmail.com"
        Phone: "+914444444446"
        Category: null
        LatitudeLongitude: null
      xml:
        name: Deliverylocation
    OnTimePriceModifier:
      type: object
      properties:
        ID:
          type: string
          description: Unique id generated by the STAT system. This is used as identifier
        Name:
          type: string
          description: The name of the ontime price
        CustomValue:
          type: number
          format: double
          description: The name of the custom value
        PercentCommissionable:
          type: number
          format: double
          description: The value of the commissionable percent
        Price:
          type: number
          format: double
          description: The value of the price
        Type:
          type: integer
          format: int32
          description: The value of the type
        Input:
          type: integer
          format: int32
          description: The value of the input
      example:
        ID: ""
        Name: ""
        CustomValue: 0
        PercentCommissionable: 0
        Price: 0
        Type: 0
        Input: 0
      xml:
        name: OnTimePriceModifier    
    CreateOrderInDto:
      type: object
      required:
        - CODAmount
        - Comments
        - DeclaredValue
        - Description
        - PriceSet
        - PurchaseOrderNumber
        - Quantity
        - SignatureType
        - Weight
      properties:
        CODAmount:
          type: number
          format: double
          description: The amount to be collected during the time of delivery 
        DeliveryCODRequired:
          type: boolean
          description: To know whether DeliveryCOD is required or not. 
        Refrigerated:
          type: boolean
          description: This tells whether the product is refrigerated before or during the shipment.  
            The possible values are “true/false”. True represents that the product is refrigerated and false demotes it is not refrigerated  
        TrackingNumber:
          type: string
          description: The tracking number acts as a unique identifier to track the package in real time during the shipment.
          minLength: 0
          maxLength: 50
        RequestedBy:
          type: string
          description: Order requester name
          minLength: 0
          maxLength: 50
        Description:
          type: string
          description: It is a free text field where the special instructions about the product, shipment can be added 
          minLength: 0
          maxLength: 2000
        Comments:
          type: string
          description: It’s a free text field to add comments  
          minLength: 0
          maxLength: 2000
        CollectionContactName:
          type: string
          description: Name of the peron from whom the package should be collected 
          minLength: 0
          maxLength: 50
        CollectionCODRequired:
          type: boolean
          description: CollectionCODRequired
        CollectionSignatureRequired:
          type: boolean
          description: Denotes whether it is required to get the signature from the person after collecting the package 
        Distance:
          type: number
          format: double
          description: Distance estimated for the delivery 
        Height:
          type: number
          format: double
          description: Height of the package 
        Width:
          type: number
          format: double
          description: Width of the package 
        Length:
          type: number
          format: double
          description: Length of the package 
        Weight:
          type: number
          format: double
          description: Weight of the package  
        Quantity:
          type: integer
          format: int32
          description: Order quantity 
        PriceSet:
          type: string
          description: PriceSet 
          minLength: 0
          maxLength: 50
        DeclaredValue:
          type: number
          format: double
          description: Order declared value
        DeliverySignatureRequired:
          type: boolean
          description: Denotes whether it is required to get the signature from the person after delivering the package 
        SuppressUserNotification:
          type: boolean
          description: This is to denote whether notification has to be sent to the user or not 
        PurchaseOrderNumber:
          type: string
          description: PurchaseOrderNumber acts as a unique identifier to track the purchase order.
          minLength: 0
          maxLength: 50
        ReferenceNumber:
          type: string
          description: ReferenceNumber acts as a unique identifier to track the package order. 
          minLength: 0
          maxLength: 50
        ShortCodeOptIn:
          type: boolean
          description: ShortCodeOptIn
        CollectionLocation:
          $ref: '#/components/schemas/Collectionlocation'
        DeliveryLocation:
          $ref: '#/components/schemas/Deliverylocation'
        PriceModifier :
          $ref: '#/components/schemas/OnTimePriceModifier'
        ShipToInjectionPoint:
          type: boolean
          description: It represents shipment to injection point is needed or not 
        ShippinglabelSize:
          type: string
          description: Size of the shipping label 
          minLength: 0
          maxLength: 50
        RXNumber:
          type: string
          description: order RXNumber describe
          minLength: 0
          maxLength: 250
        SignatureType:
          type: string
          description: Direct/Indirect 
          minLength: 0
          maxLength: 50
        IsAdultSignature:
          type: boolean
          description: Denotes the signature is received from an adult  
        IsCustomerPortal:
          type: boolean
          description: IsCustomerPortal
        IsUpdateOnTime:
          type: boolean
          description: IsUpdateOnTime
      example:
        CODAmount: 20
        DeliveryCODRequired: false
        Refrigerated: false
        TrackingNumber: ""
        RequestedBy: null
        Description: "Fragile Handle with care: Glass material"
        Comments: null
        CollectionContactName: null
        CollectionCODRequired: false
        CollectionSignatureRequired: false
        Distance: 0
        Height: 150
        Width: 200
        Length: 250
        Weight: 200
        Quantity: 1
        PriceSet: "b6ec8de4-852a-445f-8f3e-c56b8b3969b5"
        DeclaredValue: 129
        DeliverySignatureRequired: true
        SuppressUserNotification: false
        PurchaseOrderNumber: "55555"
        ReferenceNumber: null
        ShortCodeOptIn: false
        CollectionLocation:
          Zone: ""
          ID: ""
          ContactName: "Johnsons-6"
          CompanyName: "Johnsons-6"
          AddressLine1: "2334 Cedar Crest Blvd"
          AddressLine2: ""
          City: "Dallas"
          State: "TX"
          PostalCode: "75203"
          Country: "United States"
          Comments: null
          Email: "pharma@yopmail.com"
          Phone: "3333344445"
          Category: null
          LatitudeLongitude: null
        DeliveryLocation:
          Zone: ""
          ID: ""
          ContactName: "Tom Holland-525"
          CompanyName: "Medicare-525"
          AddressLine1: "9050 Markville Dr"
          AddressLine2: ""
          City: "Dallas"
          State: "TX"
          PostalCode: "75243"
          Country: "United States"
          Comments: null
          Email: "uzumaki@yopmail.com"
          Phone: "+914444444446"
          Category: null
          LatitudeLongitude: null
        PriceModifier:
          ID: ""
          Name: ""
          CustomValue: 0
          PercentCommissionable: 0
          Price: 0
          Type: 0
          Input: 0
        ShipToInjectionPoint: true
        ShippinglabelSize: ""
        RXNumber: ""
        SignatureType: "direct"
        IsAdultSignature: true
        IsCustomerPortal: true
        IsUpdateOnTime: true
      xml:
        name: CreateOrderInDto    
    
    OrderStatusDto:
      type: object
      properties:
        Date:
          type: string
          format: date-time
          description: 
        Description:
          type: string
          description: 
        Exception:
          type: boolean
          description: 
        ExceptionCode:
          type: integer
          format: int32
          description: 
        LocalTime:
          type: string
          format: date-time
          description: 
        Region:
          type: string
          description: 
      example:
        Date: "2023-09-05T15:20:38.0755622Z"
        Description: "Order received"
        Exception: false
        ExceptionCode: 0
        LocalTime: "2023-09-05T10:20:38.0755622"
        Region: Irving  
      xml:
        name: OrderStatusDto     
    CollectionArrivalWindow:
      type: object
      properties:
        EarliestTime:
          type: string
          format: date-time
          description: 
        LatestTime:
          type: string
          format: date-time
          description: 
      example:
        EarliestTime: "2023-09-05T15:20:31.539697Z"
        LatestTime: "2023-09-06T02:00:00Z"
      xml:
        name: CollectionArrivalWindow         
    DeliveryArrivalWindow:
      type: object
      properties:
        EarliestTime:
          type: string
          format: date-time
          description: 
        LatestTime:
          type: string
          format: date-time
          description: 
      example:
        EarliestTime: "2023-09-06T12:00:00Z"
        LatestTime: "2023-09-06T16:00:00Z"
      xml:
        name: DeliveryArrivalWindow 
    CreateOrderOutDto:
      type: object
      properties:
        error:
          type: string
          description:  
          minLength: 0
          maxLength: 2000
        ID:
          type: string
          description: Unique id generated by the STAT system. This is used as identifier
          minLength: 0
          maxLength: 50
        TrackingNumber:
          type: string
          description: Helps to track and get the status of the movement of the package order. 
          minLength: 0
          maxLength: 50
        TrackingURL:
          type: string
          description: 
          minLength: 0
          maxLength: 2000
        BarcodeURL:
          type: string
          description: 
          minLength: 0
          maxLength: 2000
        ShippingLabel:
          type: string
          description: The label affixed on the package gives comprehensive information regarding the shipment. 
        VpodDownload:
          type: string
          description:
        SignatureURL:
          type: string
          description:
          minLength: 0
          maxLength: 2000 
        Refrigerated:
          type: boolean
          description: This tells whether the product is refrigerated before or during the shipment.  
            The possible values are “true/false”. True represents that the product is refrigerated and false demotes it is not refrigerated  
        StatusUpdates:
          $ref: '#/components/schemas/OrderStatusDto'
        DeliveryContactName:
          type: string
          description: 
          minLength: 0
          maxLength: 50
        StatusCode:
          type: integer
          format: int32
          description: 
        CustomerAccount:
          type: string
          description:  
          minLength: 0
          maxLength: 50
        Description:
          type: string
          description: It is a free text field where the special instructions about the product, shipment can be added 
          minLength: 0
          maxLength: 2000
        Comments:
          type: string
          description: It’s a free text field to add comments  
          minLength: 0
          maxLength: 2000
        PriceSet:
          type: string
          description: PriceSet 
          minLength: 0
          maxLength: 50 
        CollectionArrivalWindow:
          $ref: '#/components/schemas/Collectionlocation'
        DeliveryArrivalWindow:
          $ref: '#/components/schemas/Deliverylocation'
        CollectionSignatureRequired:
          type: boolean
          description: Denotes whether it is required to get the signature from the person after collecting the package
        DeliverySignatureRequired:
          type: boolean
          description: Denotes whether it is required to get the signature from the person after delivering the package 
        SuppressUserNotification:
          type: boolean
          description: This is to denote whether notification has to be sent to the user or not 
        TotalCost:
          type: number
          format: double
          description:  
        DeclaredValue:
          type: number
          format: double
          description: Order declared value
      example:
        RegionCode: null
        error: null
        ID: "12735950"
        TrackingNumber: "S2023090002912"
        TrackingURL: "https://apps.statovernight.com/MyOrder/?id=nIF2IBUM_ECFnw_-W7sqpA"
        BarcodeURL: "https://statqa.azurewebsites.net/OrdersManagement/Orders/OrderShippingLabel?orderId=S2023090002912&customerId=43532938-be8d-43c3-b9c7-cc6ea8441f93"
        ShippingLabel: "https://statapi-development.azurewebsites.net//api/DownloadLabel?TrackingNumber=S2023090002912&Type=ShippingLabel&CustomerId=43532938-be8d-43c3-b9c7-cc6ea8441f93&Size=4x8"
        VpodDownload: null
        SignatureURL: null
        Refrigerated: false
        StatusUpdates: 
          Date: "2023-09-05T15:20:38.0755622Z"
          Description: "Order received"
          Exception: false
          ExceptionCode: 0
          LocalTime: "2023-09-05T10:20:38.0755622"
          Region: Irving              
        DeliveryContactName: null
        StatusCode: 1
        CustomerAccount: "78554512"
        Description: "Fragile Handle with care: Glass material"
        Comments: ""
        Customer: "1369"
        PriceSet: ""
        CollectionArrivalWindow: 
          EarliestTime: "2023-09-05T15:20:31.539697Z"
          LatestTime: "2023-09-06T02:00:00Z"
        DeliveryArrivalWindow: 
          EarliestTime: "2023-09-06T12:00:00Z"
          LatestTime: "2023-09-06T16:00:00Z"
        CollectionSignatureRequired: false
        DeliverySignatureRequired: false
        SuppressUserNotification: false
        CollectionLocation: 
          Zone: ""
          ID: ""
          ContactName: "Johnsons"
          CompanyName: "PKR pharmacy"
          AddressLine1: "2334 Cedar Crest Blvd"
          AddressLine2: null
          City: "Dallas"
          State: "TX"
          PostalCode: "75203"
          Country: "United States"
          Comments: null
          Email: "pharma@yopmail.com"
          Phone: "3333344445"
          Category: null
          LatitudeLongitude: null
        DeliveryLocation: 
          Zone: ""
          ID: ""
          ContactName: "Tom Holland"
          CompanyName: "Medicare"
          AddressLine1: "9050 Markville Dr"
          AddressLine2: null
          City: "Dallas"
          State: "TX"
          PostalCode: "75243-1254"
          Country: "United States"
          Comments: null
          Email: "sample01@yopmail.com"
          Phone: ""
          Category: null
          LatitudeLongitude: null
        DeclaredValue: 129.0
        TotalCost: 0.0
        DriverInstruction: "Drop the package at the front door"
      xml:
        name: CreateOrderOutDto                   
   
